imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ApiBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    exception_controller: 'VT\ApiBundle\Controller\ExceptionController::showAction'
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        persistent: true
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        options: {1002: "SET time_zone = '+00:00'"}
        mapping_types:
            enum:  string
            point:   point
            linestring:   linestring
            polygon:   polygon
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        # entity_managers:
        #     mappings:
        #         VTApiBundle:  ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS REST Configuration
fos_rest:
    routing_loader:
        default_format: json
    view:
        view_response_listener: force
        exception_wrapper_handler: VT\ApiBundle\Exception\VTExceptionWrapperHandler
        force_redirects:
#          html: true
        formats:
            json: true
            xml: true
        mime_types:
            html: 'text/html'
            json: ['application/json', 'application/x-json']
            rss: 'application/rss+xml'
            xml: 'application/xml'
            jpg: 'image/jpeg'
            png: 'image/png'
            css: 'text/css'
    body_listener: true
    param_fetcher_listener: force
    allowed_methods_listener: true
    format_listener:
        rules:
            # setting fallback_format to json means that instead of considering the next rule in case of a priority mismatch, json will be used
            - { path: '^/', host: '%api_subdomain%.%domain%', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
            - { path: '^/ajax/', host: '%admin_subdomain%.%domain%', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: [ 'text/html', 'text/css', 'image/png', 'image/jpg', '*/*'], fallback_format: html, prefer_extension: true }
    serializer:
            # return params with null values
            serialize_null: false
