vt_api:
    host:     '%host%'
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

login:
   path:   /login
   defaults:  { _controller: ApiBundle:Auth:login }
   options:
        expose: true

login_check:
   path:   /login_check

logout:
   path:   /logout
   options:
        expose: true
