<?php

namespace VT\ApiBundle\Repository;

/**
 * AdditionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalRepository extends \Doctrine\ORM\EntityRepository
{
}
