<?php

namespace VT\ApiBundle\Repository;

/**
 * AppEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppEventRepository extends \Doctrine\ORM\EntityRepository
{
}
