<?php

namespace VT\ApiBundle\Repository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppEventUserRepository extends \Doctrine\ORM\EntityRepository
{
}
