<?php

namespace VT\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieDocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieDocRepository extends EntityRepository
{
}
