<?php

namespace VT\ApiBundle\Repository;

/**
 * SauceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SauceRepository extends \Doctrine\ORM\EntityRepository
{
}
